name: linux-build

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Linux bits"
        value: linux-bits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    # Necessary for running neato
    - name: Install libgts
      run: sudo apt-get update && sudo apt-get install -y libgts-0.7-5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup Just
      uses: extractions/setup-just@v3

    - name: Build and test
      run: just

    - name: Check diff
      run: just check-diff

    - name: Locate nupkg
      id: pkg
      run: just locate-nupkg "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v4
      with:
        name: linux-bits
        path: ${{ steps.pkg.outputs.package }}
        retention-days: 3
