name: linux-build

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Linux bits"
        value: linux-bits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    # Necessary for running neato
    - name: Install libgts
      run: sudo apt-get update && sudo apt-get install -y libgts-0.7-5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Restore NuGet Packages
      run: dotnet restore Rubjerg.Graphviz.sln

    - name: Print PWD
      run: pwd

    - name: Build App
      run: dotnet build Rubjerg.Graphviz.sln --configuration Release --no-restore

    - name: Build App Another Time because dot net sucks and cannot see the native dependencies the first time
      run: dotnet build Rubjerg.Graphviz.sln --configuration Release --no-restore

    - name: Debug Intermediate Output
      run: ls -la /home/runner/work/Graphviz.NetWrapper/Graphviz.NetWrapper/Rubjerg.Graphviz/Resources

    - name: Debug Build Output
      run: ls -la /home/runner/work/Graphviz.NetWrapper/Graphviz.NetWrapper/Rubjerg.Graphviz/bin/x64/Release/netstandard2.0/

    - name: Restore (just built) NuGet Packages for Tests
      run: dotnet restore Rubjerg.Graphviz.Tests.sln

    - name: Build Tests
      run: dotnet build Rubjerg.Graphviz.Tests.sln --configuration Release --no-restore

    - name: Run Unittests
      run: bash run-tests-netcore.sh Rubjerg.Graphviz.Test/Rubjerg.Graphviz.Test.csproj

    - name: Run Transitive Tests
      run: bash run-tests-netcore.sh Rubjerg.Graphviz.TransitiveTest/Rubjerg.Graphviz.TransitiveTest.csproj

    - name: Locate nupkg
      id: pkg
      run: |
        pkg=$(find . -name "Rubjerg.Graphviz.*.nupkg" | head -1)
        echo "package=$pkg" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v4
      with:
        name: linux-bits
        path: ${{ steps.pkg.outputs.package }}
        retention-days: 3
