name: linux-build

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Linux bits"
        value: linux-bits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    # Necessary for running neato
    - name: Install libgts
      run: sudo apt-get update && sudo apt-get install -y libgts-0.7-5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup Just
      uses: extractions/setup-just@v3

    - name: Restore tools
      run: just restore-tools

    - name: Restore NuGet packages
      run: just restore

    - name: Build app
      run: just build-package

    - name: Restore NuGet packages for tests
      run: just restore-tests

    - name: Build tests
      run: just build-tests

    - name: Run unit tests (.NET 8)
      shell: bash
      run: just test Rubjerg.Graphviz.Test/Rubjerg.Graphviz.Test.csproj

    - name: Run transitive tests (.NET 8)
      shell: bash
      run: just test Rubjerg.Graphviz.TransitiveTest/Rubjerg.Graphviz.TransitiveTest.csproj

    - name: Locate nupkg
      id: pkg
      run: |
        pkg=$(find . -name "Rubjerg.Graphviz.*.nupkg" | head -1)
        echo "package=$pkg" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v4
      with:
        name: linux-bits
        path: ${{ steps.pkg.outputs.package }}
        retention-days: 3
