# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# https://timheuer.com/blog/building-net-framework-apps-using-github-actions/
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore Rubjerg.Graphviz.sln

    - name: Build App
      run: msbuild Rubjerg.Graphviz.sln /p:Configuration=Release

    - name: Check if README is up-to-date
      run: git diff --exit-code -- README.md

    - name: Run Unittests
      run: .\packages\nunit.consolerunner.3.11.1\tools\nunit3-console.exe Rubjerg.Graphviz.Test\bin\Release\Rubjerg.Graphviz.Test.dll --where cat!=Slow and cat!=Flaky

    - name: Run Nuget Tests
      run: packages\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe Rubjerg.Graphviz.NugetTest\bin\Release\Rubjerg.Graphviz.NugetTest.dll

    - name: Run Unittests Coverage (Separate step because OpenCover doesn't seem to propagate return codes)
      run: packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register -target:"packages\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe" -targetargs:"Rubjerg.Graphviz.Test\bin\Release\Rubjerg.Graphviz.Test.dll --where cat!=Slow and cat!=Flaky" -output:".\coverage.xml" -filter:"+[Rubjerg*]* -[Rubjerg.Graphviz.Test*]*"

    - name: Upload Coverage data
      run: |
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh -f "coverage.xml"

