# This is a basic workflow to help you get started with Actions

name: nuget.org-linux

on:
  push:         { branches: [ master ] }
  pull_request: { branches: [ master ] }
  release:      { types: [published] }      # runs on “Publish release” button
  workflow_dispatch:                        # lets you run it by hand

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
      with:
        fetch-depth: 0

    # Necessary for running neato
    - name: Install libgts
      run: sudo apt-get update && sudo apt-get install -y libgts-0.7-5

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Just
      uses: extractions/setup-just@v3

    - name: Build and test
      run: just test-nugetorg
